### ISSUE TITLE
Responsive canvas problem

### ISSUE THREAD

**Issue by devon** [Leimi/drawingboard.js#33]
The line is stranger after resize the canvas. Check the image: http://cl.ly/image/2W0t2v2N1B3L.

I resize the canvas with css width and height.

**Comment by officiallyemma** [comment]
7 years later and this just saved me hours of headaches. Thanks!

**Comment by officiallyemma** [comment]
The link above has expired, for time's sake here is a new link showing this issue. [![https://imgur.com/17nOG9S.png](https://imgur.com/17nOG9S.png)](https://imgur.com/17nOG9S.png)
