### ISSUE TITLE
Download file's file extensions

### ISSUE THREAD

**Issue by xuchenhao001** [Leimi/drawingboard.js#57]
When I offer my drawingboard a "Download" option, someone can download his drawing. I have tried to open it with a photo viewer and it's okay. However, there isn't a file extension after file name. I consider it may confuse other users. 
Hope to have an argument to fix that.

**Comment by Ensanho** [comment]
downloadImg: function() {
		var img = this.getImg();
		img = img.replace("image/png", "image/octet-stream");
		var link = document.createElement('a');
		link.download = "your file name.png/jpg....";
		link.href = img;
		link.click();
	},
